[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2023-03-17"              # day before a pr broke objc2 https://github.com/madsmtm/objc2/issues/432
components = ["cargo", "clippy", "rustfmt"]
