[toolchain]
# https://rust-lang.github.io/rustup-components-history/
# For nightly, swap to: channel = "nightly" (or pin a date, e.g. "nightly-2025-06-20")
channel = "stable"
components = ["cargo", "clippy", "rustfmt"]
